# Generated by Django 4.2.17 on 2024-12-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_artist_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.country'),
        ),
    ]
