# Generated by Django 4.2.17 on 2024-12-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_album_cover_image_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
