# Generated by Django 4.2.17 on 2024-12-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lyrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lyrics',
            options={'verbose_name_plural': 'Lyrics'},
        ),
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.CharField(max_length=255),
        ),
    ]
